import LegalPageLayout from "../components/LegalPageLayout";

export default function TermsOfUsePage() {
  return (
    <LegalPageLayout title="Terms of Use" lastUpdated="27 August 2026">
      <p>
        These Terms of Use ("Terms") govern access to and use of the TalentIQ recruitment platform
        ("TalentIQ", "the Platform", "we", "us"), including the recruiter-facing application, the
        public candidate-facing pages (job applications, video and phone interviews, hiring-manager
        review links, vendor and client portals), and all related services. By creating an account,
        accessing the Platform, or completing any candidate-facing flow (such as a job application or
        video interview), you agree to be bound by these Terms. If you do not agree, do not use the
        Platform.
      </p>

      <h2>1. Who these Terms apply to</h2>
      <p>TalentIQ is used by several distinct groups of people, and different sections of these Terms apply depending on your role:</p>
      <ul>
        <li><strong>Recruiters and hiring teams</strong> — employees or contractors of a company (an "Organisation") that has registered for a TalentIQ account to manage requisitions, screen candidates, and run interviews.</li>
        <li><strong>Candidates</strong> — individuals who apply for a role, submit a résumé, or complete a phone or video interview through a link generated by an Organisation using TalentIQ, whether or not they ever create a TalentIQ account themselves.</li>
        <li><strong>Hiring managers, clients, and vendors</strong> — individuals who access a scoped, token-based portal (e.g. a hiring-manager review link, a client portal, or a vendor portal) shared by an Organisation, without a full TalentIQ login.</li>
      </ul>
      <p>
        Where an Organisation uses TalentIQ to interact with candidates, hiring managers, clients, or
        vendors, that Organisation is responsible for how it uses the Platform and for its own
        compliance with employment, privacy, and consumer-protection laws applicable to its hiring
        process. TalentIQ acts as the technology provider and, with respect to candidate personal data,
        generally as a data processor acting on the Organisation's instructions — see our
        <a href="/privacy"> Privacy Policy</a> for more detail on this relationship.
      </p>

      <h2>2. Accounts and access</h2>
      <p>
        Organisations and their users are responsible for maintaining the confidentiality of login
        credentials and for all activity that occurs under their account. Access to certain
        functionality (for example, platform-wide API keys, global scoring configuration, or user
        management) is restricted to users with the "admin" role within an Organisation's account, as
        configured by that Organisation.
      </p>
      <p>
        Candidate-facing, hiring-manager, client, and vendor links generated by the Platform (for
        example, video interview links, hiring-manager view links, or portal links) use unguessable,
        randomly generated tokens rather than passwords. You must not share these links with anyone
        other than their intended recipient, and you should treat them as you would a password.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to use the Platform to:</p>
      <ul>
        <li>Violate any applicable law, including anti-discrimination, employment, or data protection law;</li>
        <li>Upload or process personal data you are not lawfully entitled to collect or share;</li>
        <li>Attempt to gain unauthorised access to another Organisation's data, another candidate's records, or any account, token, or link that does not belong to you;</li>
        <li>Interfere with, disrupt, or attempt to reverse-engineer the Platform, its AI scoring models, or its underlying infrastructure;</li>
        <li>Use the Platform's AI features (résumé scoring, interview question generation, video/emotion analysis, or transcription) as the sole or determinative basis for an adverse employment decision, without human review — see Section 5 below; or</li>
        <li>Upload malicious code, attempt to probe for security vulnerabilities other than through a responsible disclosure process, or otherwise abuse the service.</li>
      </ul>

      <h2>4. Video and phone interviews</h2>
      <p>
        Where an Organisation invites a candidate to complete a video interview through TalentIQ, the
        candidate is shown a privacy notice describing that the session will be recorded, stored, and
        reviewed, and must affirmatively accept that notice before camera or microphone access is
        requested. TalentIQ will not record a candidate's video interview without this acceptance
        being recorded first.
      </p>
      <p>
        Recorded interview video, audio, and any derived transcript or analysis are stored as
        described in our <a href="/data-security">Data Security</a> page and our
        <a href="/privacy"> Privacy Policy</a>, and are made available only to the Organisation that
        generated the interview (and to TalentIQ personnel or systems as needed to operate the
        Platform). Candidates should complete video interviews from a private location and understand
        that questions may be read aloud using a synthesised ("text-to-speech") voice as part of the
        interview experience.
      </p>

      <h2>5. AI-assisted screening — human oversight</h2>
      <p>
        TalentIQ provides AI-assisted features to help Organisations work through high volumes of
        applications more efficiently: résumé-to-job-description scoring, generated interview
        questions, and analysis of interview transcripts and recorded video (including facial-emotion
        signals and derived communication/relevance/confidence scores). These features are decision
        <em> support</em> tools.
      </p>
      <p>
        TalentIQ does not itself make hiring decisions. Every scoring output, recommendation, or
        analysis produced by the Platform is presented to a human recruiter or hiring manager for
        review, and the Organisation using the Platform remains solely responsible for all hiring
        decisions, and for ensuring that its use of AI-assisted screening complies with applicable law
        in the jurisdictions where it hires (including any laws specifically governing automated
        employment decision tools).
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        The Platform, including its software, design, and AI models and prompts, is owned by TalentIQ
        or its licensors and is protected by intellectual property laws. Organisations retain all
        rights to the data they upload (job descriptions, candidate records, requisitions, and so on).
        Candidates retain all rights to their own résumé, video, and other submitted materials, subject
        to the licence in Section 7 below.
      </p>

      <h2>7. Licence to process your content</h2>
      <p>
        By uploading a résumé, job description, or other document, or by completing a phone or video
        interview, you grant TalentIQ and the relevant Organisation a limited licence to store,
        process, transcribe, analyse, and display that content solely for the purpose of operating the
        Platform and supporting that Organisation's recruitment process. This licence ends when the
        content is deleted in accordance with the Organisation's data retention practice or applicable
        law.
      </p>

      <h2>8. Disclaimers and limitation of liability</h2>
      <p>
        The Platform is provided "as is" and "as available." To the maximum extent permitted by law,
        TalentIQ disclaims all warranties, express or implied, including fitness for a particular
        purpose and non-infringement, and does not warrant that AI-generated scores, transcripts, or
        analyses are accurate, complete, or free of bias. To the maximum extent permitted by law,
        TalentIQ's aggregate liability arising out of or relating to these Terms or use of the Platform
        will not exceed the amount paid by the relevant Organisation to TalentIQ in the twelve (12)
        months preceding the claim.
      </p>

      <h2>9. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time to reflect changes to the Platform or applicable
        law. Material changes will be indicated by updating the "Last updated" date above. Continued
        use of the Platform after changes take effect constitutes acceptance of the revised Terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms can be directed to your Organisation's TalentIQ administrator, or
        to TalentIQ support through the channel your Organisation uses to reach us.
      </p>
    </LegalPageLayout>
  );
}
